language: python
python:
- 3.6

matrix:
  include:
  - name: trusty
    os: linux
    dist: trusty
    env: 
      - PYTHON_EXECUTABLE=~/virtualenv/python3.6/bin/python
  - name: xenial
    os: linux
    dist: xenial
    env: 
      - PYTHON_EXECUTABLE=~/virtualenv/python3.6/bin/python
  - name: g++8
    os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-8
    before_install:
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 90
    env: 
      - PYTHON_EXECUTABLE=~/virtualenv/python3.6/bin/python
  - name: osx
    os: osx
    language: generic
    before_install:
    - brew install llvm libomp
    - python3 -m pip install virtualenv
    - virtualenv venv -p python3
    - source venv/bin/activate
    env:
      - PYTHON_EXECUTABLE=../venv/bin/python
      - HOMEBREW_NO_AUTO_UPDATE=1
      - CC=/usr/local/opt/llvm/bin/clang
      - CXX=/usr/local/opt/llvm/bin/clang++

install:
- pip install -r requirements.txt

script:
- mkdir build
- cd build
- cmake .. -DCMAKE_BUILD_TYPE=Release -DSTK_BUILD_TESTS=1
  -DSTK_BUILD_PYTHON_WRAPPER=ON -DPYTHON_EXECUTABLE=$PYTHON_EXECUTABLE
- cmake --build . --config Release
- ctest --output-on-failure
- cd ..
- python setup.py install
- python -m unittest discover test
