language: cpp

matrix:
  include:
  - os: linux
    dist: trusty
    name: gcc 4.8
    env: GCC=4.8

script:
- mkdir build
- cd build
- cmake .. -DCMAKE_BUILD_TYPE=Release -DSTK_BUILD_TESTS=1 -DSTK_WARNINGS_ARE_ERRORS=1
- cmake --build . --config Release
- ctest --output-on-failure