language: cpp

matrix:
  fast_finish: true
  include:
  - os: linux
    dist: trusty
  - os: linux
    dist: xenial

script:
- mkdir build
- cd build
- cmake .. -DCMAKE_BUILD_TYPE=Release -DSTK_BUILD_TESTS=1 -DSTK_WARNINGS_ARE_ERRORS=1
- cmake --build . --config Release
- ctest --output-on-failure