language: cpp

matrix:
  fast_finish: true
  include:
  - os: linux
    dist: trusty
  - os: linux
    dist: xenial
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
    env:
      - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
    env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

script:
- mkdir build
- cd build
- cmake .. -DCMAKE_BUILD_TYPE=Release -DSTK_BUILD_TESTS=1 -DSTK_WARNINGS_ARE_ERRORS=1
- cmake --build . --config Release
- ctest --output-on-failure